create table if not exists fields (
    session char(2),
    due_date char(10),
    data text,
    primary key (session, due_date)
);

create table if not exists defaults (
    data text
);

create table if not exists empty_data (
    data text
);

create table if not exists time_entries (
    id int not null auto_increment,
    start timestamp not null,
    end timestamp not null,
    user_id int not null,
    task_id text not null,
    task_url text not null,
    primary key (id)
);

insert into defaults (data)
values ('{"sessions":{"s6":{"objective":["Électrique: Avoir une base pour tout ce qui est alimentation (prototype conceptuel)","Informatique: Architecture globale avec une solution pour la communication","Mécanique: Avoir toutes les parties du système dans un environnement simulé (CAD)"]},"s7":{"objective":["Possibilité de déployer un prototype à l''été - MVP1 complet, MVP2 bien avancé / complet"]}},"members":[{"img":"daniel.jpg","firstname":"Daniel","lastname":"B","role":"Médiateur"},{"img":"ariel.png","firstname":"Ariel","lastname":"M F","role":"Correcteur"},{"img":"zachary.png","firstname":"Zachary","lastname":"G","role":"Animateur"},{"img":"simon.jpg","firstname":"Simon","lastname":"L","role":"Chef d''équipe"},{"img":"natael.jpg","firstname":"Nataël","lastname":"L-L","role":"Vérificateur"},{"img":"mederick.jpg","firstname":"Médérick","lastname":"M","role":"Gestionnaire"},{"img":"julien.png","firstname":"Julien","lastname":"R","role":"Secrétaire"}]}');

insert into empty_data (data)
values ('{"members":[{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}}],"meeting":{"date":"Saisir une date de remise ici","agenda":{"items":[]},"technical":{"items":[]}},"risks":[],"sprint":{"id":"Saisir l''id du sprint''","objective":"","problems":[]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-06-15', '{"objective":"Insérer un objectif pour la semaine ici","members":[{"disponibility":{"lastWeek":1,"nextWeek":4}},{"disponibility":{"lastWeek":2,"nextWeek":3}},{"disponibility":{"lastWeek":3,"nextWeek":2}},{"disponibility":{"lastWeek":4,"nextWeek":1}},{"disponibility":{"lastWeek":5,"nextWeek":2}},{"disponibility":{"lastWeek":4,"nextWeek":3}},{"disponibility":{"lastWeek":3,"nextWeek":4}},{"disponibility":{"lastWeek":2,"nextWeek":5}}],"meeting":{"date":"1 juin 2023 - 14h00","agenda":{"items":["test 1","test 2","test 3","test 4"]},"technical":{"items":["tech 1","tech 2","tech 3","tech 4"]}},"risks":[{"description":"risque no1","mitigation":"on fait ça","gravity":5,"ticketUrl":"https://app.clickup.com/t/860qx97ax"},{"description":"risque no2 da awd wawdada da a a da dadwwd a","mitigation":"on fait qqch d''autre","gravity":1}],"sprint":{"id":"901100134863","objective":"","problems":[]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-06-22', '{"members":[{"disponibility":{"lastWeek":1,"nextWeek":3}},{"disponibility":{"lastWeek":1,"nextWeek":3}},{"disponibility":{"lastWeek":5,"nextWeek":4}},{"disponibility":{"lastWeek":2,"nextWeek":5}},{"disponibility":{"lastWeek":3,"nextWeek":3}},{"disponibility":{"lastWeek":1,"nextWeek":5}},{"disponibility":{"lastWeek":2,"nextWeek":5}},{"disponibility":{"lastWeek":4,"nextWeek":4}}],"meeting":{"date":"22 juin 2023 - 10h20","agenda":{"items":["SARIC","Communication avec A. Tessier","Rétroaction sur le MIP","Réf. télécommunication"]},"technical":{"items":["Batteries (type)","Cutoff (alimentation)","Design modulaire","Contrôleur (recherches)"]}},"risks":[{"description":"L''accès rapide et le coût à des système faisant de la communication satellite.","mitigation":"Analyse approfondie des différentes manières de communiquer ainsi que des systèmes","gravity":3,"ticketUrl":"https://app.clickup.com/t/8684w7eqj"},{"description":"Problème de transport de batteries par avion.","mitigation":"Vérifier avec l''université des procédures liées aux matières dangereuses","gravity":3,"ticketUrl":"https://app.clickup.com/t/8684w9p3w"},{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques.","mitigation":"Effectuer des tests au 3IT","gravity":6,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":8}],"sprint":{"id":"901100134863","objective":"Décider sur quelles possibilités se concentrer pour l''alimentation et la communication.","problems":[{"taskId":"8684w99t1","description":"Un exemple de problème qui bloquerait cette tâche avec des informations intéressantes ici"}]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-06-29', '{"members":[{"disponibility":{"lastWeek":3,"nextWeek":3}},{"disponibility":{"lastWeek":3,"nextWeek":3}},{"disponibility":{"lastWeek":4,"nextWeek":4}},{"disponibility":{"lastWeek":5,"nextWeek":5}},{"disponibility":{"lastWeek":3,"nextWeek":3}},{"disponibility":{"lastWeek":5,"nextWeek":3}},{"disponibility":{"lastWeek":5,"nextWeek":3}},{"disponibility":{"lastWeek":4,"nextWeek":4}}],"meeting":{"date":"29 juin 2023 - 10h20","agenda":{"items":["Choix du concept","Planification sprint 1","Évaluation rencontre","Avancement communication"]},"technical":{"items":["Options télécommunication","Choix & critères","Dispositifs disponibles"]}},"risks":[{"description":"L''accès rapide et le coût à des système faisant de la communication satellite.","mitigation":"Analyse approfondie des différentes manières de communiquer ainsi que des systèmes","gravity":1,"ticketUrl":"https://app.clickup.com/t/8684w7eqj"},{"description":"Problème de transport de batteries par avion.","mitigation":"Vérifier avec l''université des procédures liées aux matières dangereuses","gravity":3,"ticketUrl":"https://app.clickup.com/t/8684w9p3w"},{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":8},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"}],"sprint":{"id":"901100134863","objective":"Décider sur quoi se concentrer pour l''alimentation et la communication. CAD le boitier.","problems":[{"taskId":"8684w9ta4","description":"Dépend de la batterie, des PCBs et de l''isolation."}]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-07-06', '{"members":[{"disponibility":{"lastWeek":3,"nextWeek":5}},{"disponibility":{"lastWeek":3,"nextWeek":5}},{"disponibility":{"lastWeek":4,"nextWeek":3}},{"disponibility":{"lastWeek":5,"nextWeek":3}},{"disponibility":{"lastWeek":3,"nextWeek":3}},{"disponibility":{"lastWeek":3,"nextWeek":4}},{"disponibility":{"lastWeek":3,"nextWeek":4}},{"disponibility":{"lastWeek":4,"nextWeek":3}}],"meeting":{"date":"6 juillet 2023 - 10h20","agenda":{"items":["CAD (submergé)","Légalité LTE","Rencontre Myriota"]},"technical":{"items":["Choix matériaux","Choix solution","Flottabilité"]}},"risks":[{"description":"Problème de transport de batteries par avion.","mitigation":"Vérifier avec l''université des procédures liées aux matières dangereuses","gravity":3,"ticketUrl":"https://app.clickup.com/t/8684w9p3w"},{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":8},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":5},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"}],"sprint":{"id":"901100134863","objective":"Décider sur quoi se concentrer pour l''alimentation et la communication. CAD le boitier.","problems":[{"taskId":"8684w9ta4","description":"Dépend de la batterie, des PCBs et de l''isolation."},{"taskId":"8684w7j8r","description":"Rencontre avec Myriota à planifier (semaine du 10 juillet)"}]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-07-13', '{"members":[{"disponibility":{"lastWeek":5,"nextWeek":2}},{"disponibility":{"lastWeek":5,"nextWeek":2}},{"disponibility":{"lastWeek":3,"nextWeek":4}},{"disponibility":{"lastWeek":3,"nextWeek":3}},{"disponibility":{"lastWeek":3,"nextWeek":3}},{"disponibility":{"lastWeek":4,"nextWeek":2}},{"disponibility":{"lastWeek":4,"nextWeek":4}},{"disponibility":{"lastWeek":3,"nextWeek":3}}],"meeting":{"date":"13 juillet 2023 - 10h20","agenda":{"items":["Retour MIP","Retour Myriota","Retour sonar","Transferts thermiques","Architecture info"]},"technical":{"items":["Architecture","MCU","Cutoff","Consommation batteries"]}},"risks":[{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":8},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":3},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"},{"description":"Échec du système de flottabilité","mitigation":"Surdimensionner les flotteurs","gravity":5}],"sprint":{"id":"901100235038","objective":"Faire le CAD de la base extérieure. Développer une architecture complète du projet. Choix final pour communication.","problems":[{"taskId":"8684w9ta4","description":"Dépend de la batterie et des PCBs."}]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-07-20', '{"members":[{"disponibility":{"lastWeek":2,"nextWeek":3}},{"disponibility":{"lastWeek":2,"nextWeek":4}},{"disponibility":{"lastWeek":4,"nextWeek":4}},{"disponibility":{"lastWeek":3,"nextWeek":2}},{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":2,"nextWeek":3}},{"disponibility":{"lastWeek":4,"nextWeek":2}},{"disponibility":{"lastWeek":3,"nextWeek":4}}],"meeting":{"date":"20 juillet 2023 - 10h20","agenda":{"items":["MAJ Horaire","Contraintes mécaniques"]},"technical":{"items":["Suivi communication","Architecture haut/bas niveau","Gestion des données"]}},"risks":[{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":9},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":3},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":7,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"},{"description":"Échec du système de flottabilité","mitigation":"Surdimensionner les flotteurs","gravity":5}],"sprint":{"id":"901100235038","objective":"Faire le CAD de la base extérieure. Développer une architecture complète du projet. Choix final pour communication.","problems":[{"taskId":"8684xxv98","description":"Nécessite les spécifications exactes des composantes"},{"taskId":"86850a74n","description":"Dépend de LTE (clients) + sonar"}]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-07-27', '{"members":[{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":4,"nextWeek":1}},{"disponibility":{"lastWeek":4,"nextWeek":3}},{"disponibility":{"lastWeek":2,"nextWeek":2}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":2}},{"disponibility":{"lastWeek":2,"nextWeek":3}},{"disponibility":{"lastWeek":4,"nextWeek":3}}],"meeting":{"date":"27 juillet 2023 - 10h20","agenda":{"items":["Clarifications audit 1","Choix communication","Schéma élec","Plans de validation"]},"technical":{"items":["Choix boitiers","Étanchéité des fils","Système de ramassage de la base submergée"]}},"risks":[{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":9},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":3},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":7,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"},{"description":"Échec du système de flottabilité","mitigation":"Surdimensionner les flotteurs","gravity":5}],"sprint":{"id":"901100235038","objective":"Faire le CAD de la base extérieure. Développer une architecture complète du projet. Choix final pour communication.","problems":[{"taskId":"8684xxv98","description":"Nécessite les spécifications exactes des composantes"},{"taskId":"86850a74n","description":"Dépend de sonar"}]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-08-03', '{"members":[{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":2,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":2,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}}],"meeting":{"date":"3 août 2023 - 12h45","agenda":{"items":["Audit 1"]},"technical":{"items":["Aucune rencontre technique"]}},"risks":[{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":9},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":3},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":7,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"},{"description":"Échec du système de flottabilité","mitigation":"Surdimensionner les flotteurs","gravity":5}],"sprint":{"id":"901100391231","objective":"RPC + Audit","problems":[{"taskId":"8684xxv98","description":"Nécessite les spécifications exactes des composantes"},{"taskId":"86850a74n","description":"Dépend de sonar"}]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-08-10', '{"members":[{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":2,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":2,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}}],"meeting":{"date":"3 août 2023 - 12h45","agenda":{"items":["RPC"]},"technical":{"items":["Aucune rencontre technique"]}},"risks":[{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":9},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":3},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":7,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"},{"description":"Échec du système de flottabilité","mitigation":"Surdimensionner les flotteurs","gravity":5}],"sprint":{"id":"901100391231","objective":"RPC","problems":[{"taskId":"8684xxv98","description":"Nécessite les spécifications exactes des composantes"},{"taskId":"86850a74n","description":"Dépend de sonar"}]}}');

insert into fields (session, due_date, data)
values ('s6', '2023-08-17', '{"members":[{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":2,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":2,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}}],"meeting":{"date":"3 août 2023 - 12h45","agenda":{"items":["RPC"]},"technical":{"items":["Aucune rencontre technique"]}},"risks":[{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":9},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":3},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":7,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"},{"description":"Échec du système de flottabilité","mitigation":"Surdimensionner les flotteurs","gravity":5}],"sprint":{"id":"901100391231","objective":"RPC","problems":[{"taskId":"8684xxv98","description":"Nécessite les spécifications exactes des composantes"},{"taskId":"86850a74n","description":"Dépend de sonar"}]}}');

insert into fields (session, due_date, data)
values ('s7', '2024-01-04', '{"members":[{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":2,"nextWeek":1}},{"disponibility":{"lastWeek":1,"nextWeek":1}},{"disponibility":{"lastWeek":2,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":1}}],"meeting":{"date":"3 août 2023 - 12h45","agenda":{"items":["RPC"]},"technical":{"items":["Aucune rencontre technique"]}},"risks":[{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":8,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":9},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":3},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":7,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"},{"description":"Échec du système de flottabilité","mitigation":"Surdimensionner les flotteurs","gravity":5}],"sprint":{"id":"901100391231","objective":"RPC","problems":[{"taskId":"8684xxv98","description":"Nécessite les spécifications exactes des composantes"},{"taskId":"86850a74n","description":"Dépend de sonar"}]}}');

insert into fields (session, due_date, data)
values ('s7', '2024-01-08', '{"members":[{"disponibility":{"lastWeek":5,"nextWeek":4}},{"disponibility":{"lastWeek":4,"nextWeek":4}},{"disponibility":{"lastWeek":5,"nextWeek":5}},{"disponibility":{"lastWeek":5,"nextWeek":4}},{"disponibility":{"lastWeek":5,"nextWeek":4}},{"disponibility":{"lastWeek":5,"nextWeek":3}},{"disponibility":{"lastWeek":5,"nextWeek":5}},{"disponibility":{"lastWeek":5,"nextWeek":5}}],"meeting":{"date":"8 janvier 2024 - 10h00","agenda":{"items":["Retour sur le stage","Modalités du tableau de bord"]},"technical":{"items":["Overview du PCB"]}},"risks":[{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":6,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":9},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":3},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":5,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"},{"description":"Échec du système de flottabilité","mitigation":"Surdimensionner les flotteurs","gravity":7},{"description":"Espace flash insuffisante (64kB)","mitigation":"Plusieurs binaires différents + programmeur externe","gravity":3}],"sprint":{"id":"901102510252","objective":"Commande des PCBs. Plans de tests boitier + design node sonar. Stockage + terminer capteurs.","problems":[{"taskId":"8684xxv98","description":"Nécessite le routage final du PCB submergé"},{"taskId":"86850a74n","description":"Dépend de sonar"}]}}');

insert into fields (session, due_date, data)
values ('s7', '2024-01-15', '{"members":[{"disponibility":{"lastWeek":4,"nextWeek":1}},{"disponibility":{"lastWeek":5,"nextWeek":4}},{"disponibility":{"lastWeek":4,"nextWeek":4}},{"disponibility":{"lastWeek":4,"nextWeek":1}},{"disponibility":{"lastWeek":3,"nextWeek":3}},{"disponibility":{"lastWeek":5,"nextWeek":5}},{"disponibility":{"lastWeek":5,"nextWeek":4}}],"meeting":{"date":"15 janvier 2024 - 10h00","agenda":{"items":["Suivi rencontre clients","Tour de table","Retour spécialistes - (VP?)","FEPRAP"]},"technical":{"items":["Étanchéité","Câble d''attache","Plans de tests"]}},"risks":[{"description":"Les composants utilisés ne sont pas adaptés pour les températures nordiques. (-40C sur datasheet)","mitigation":"Effectuer des tests au 3IT. Analyser les solutions mécaniques possibles.","gravity":6,"ticketUrl":"https://app.clickup.com/t/8684w9ny8"},{"description":"Gestion des pertes (alimentation)","mitigation":"Design de cutoff électrique pour tous les périphériques (rencontre technique)","gravity":9},{"description":"La communication sous l''eau n''est pas réalisable","mitigation":"Rechercher des solutions existantes / Plan B filaire","gravity":10,"ticketUrl":"https://app.clickup.com/t/8684y1gu2"},{"description":"Déplacement de la base submergée","mitigation":"Simuler et tester le comportement du lest","gravity":3},{"description":"La base submergée n''est pas étanche","mitigation":"Utiliser une solution commercialisée et l''améliorer selon nos besoins","gravity":4,"ticketUrl":"https://app.clickup.com/t/8684w9tf5"},{"description":"Échec du système de flottabilité","mitigation":"Surdimensionner les flotteurs","gravity":7},{"description":"Espace flash insuffisante (64kB)","mitigation":"Plusieurs binaires différents + programmeur externe","gravity":3}],"sprint":{"id":"901102510252","objective":"Commande des PCBs. Plans de tests boitier + design node sonar. Stockage + terminer capteurs.","problems":[{"taskId":"8684xxv98","description":"Nécessite une revue du PCB submergé"},{"taskId":"86850a74n","description":"Dépend de sonar"}]}}');

